version: '1.0'
services:
  webapp:
    image: illectronic/docker-tomcat-mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
    ports:
      - "80:8080"
    networks:
    - celsius
    environment:
      MYSQL_HOST: localhost
      MYSQL_PASS: 
